### ISSUE TITLE
Peer connected, but dont start sealing blocks. 

### ISSUE THREAD

**Issue by Moka51** [0xPolygon/polygon-edge#936] opened 2022-11-19 20:21 UTC
# [ Subject of the issue ]
## Description
I have two instances in two diferentes VPS, one instance have 3 nodes and the other instance run only 1. 
All data dir have been properly initialize and the peers are connected between VPS. Firewall have been disable and ports open via UFW in both VPS. 
## Your environment
- OS and version. Ubuntu 28.04
- The version of the Polygon Edge.    Last Branch. 
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue. Last
- Locally or Cloud hosted (which provider). Clouding VPS + Hetzner. 
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.). 
- The validator are running under binary. 

## Steps to reproduce

- Is the chain producing blocks and serving customers atm? No, peers looks connected between the two VPS but dont start the sealing work. 
- Launch the node with debug, and show this: 
[
DEBUG] polygon.network.discovery: Found new near peers: peer=2

## Expected behavior
- Start the network and mint new blocks. 

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

INSTANCE HETZNER (3 nodes) 
2022-11-19T21:20:27.022+0100 [DEBUG] polygon.network.discovery: Found new near peers: peer=2
2022-11-19T21:20:31.989+0100 [DEBUG] polygon.network.discovery: running regular peer discovery: peer=16Uiu2HAmVjyit47NpqnRMdoV5RtzGVcyh7i7QAo135Tzs5otBvyt
2022-11-19T21:20:31.989+0100 [DEBUG] polygon.network.discovery: Querying a peer for near peers: peer=16Uiu2HAmVjyit47NpqnRMdoV5RtzGVcyh7i7QAo135Tzs5otBvyt
2022-11-19T21:20:32.022+0100 [DEBUG] polygon.network.discovery: Found new near peers: peer=2
2022-11-19T21:20:36.989+0100 [DEBUG] polygon.network.discovery: running regular peer discovery: peer=16Uiu2HAmE2mHi7ZUtnM25EkSoP1HuHTUNFLz9HKzLVzgiJtHYJmk
2022-11-19T21:20:36.989+0100 [DEBUG] polygon.network.discovery: Querying a peer for near peers: peer=16Uiu2HAmE2mHi7ZUtnM25EkSoP1HuHTUNFLz9HKzLVzgiJtHYJmk
2022-11-19T21:20:36.989+0100 [DEBUG] polygon.network.discovery: Found new near peers: peer=2
2022-11-19T21:20:41.989+0100 [DEBUG] polygon.network.discovery: running regular peer discove

INSTANCE CLOUDING (1 node)
2022-11-19T21:20:29.829+0100 [DEBUG] polygon.network.discovery: Found new near peers: peer=2
2022-11-19T21:20:34.796+0100 [DEBUG] polygon.network.discovery: running regular peer discovery: peer=16Uiu2HAm4tij4PrbavucVFj1NdCLqQJSWTzHdCvZsa8bbZjbKKYd
2022-11-19T21:20:34.796+0100 [DEBUG] polygon.network.discovery: Querying a peer for near peers: peer=16Uiu2HAm4tij4PrbavucVFj1NdCLqQJSWTzHdCvZsa8bbZjbKKYd
2022-11-19T21:20:34.830+0100 [DEBUG] polygon.network.discovery: Found new near peers: peer=2
2022-11-19T21:20:39.796+0100 [DEBUG] polygon.network.discovery: running regular peer discovery: peer=16Uiu2HAmKXfZsTkmz87B15dLHBVwbPHef2hj2vq7PKUV2JttcbMA
2022-11-19T21:20:39.796+0100 [DEBUG] polygon.network.discovery: Querying a peer for near peers: peer=16Uiu2HAmKXfZsTkmz87B15dLHBVwbPHef2hj2vq7PKUV2JttcbMA
2022-11-19T21:20:39.829+0100 [DEBUG] polygon.network.discovery: Found new near peers: peer=2

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by laviniat1996** [comment] 2022-11-20 17:17
Hi @Moka51 ,

It looks that there is a peer connecitvity issue. The peers find each other, but don't seem to connect to each other, thus not producing blocks. Please check your network setup and your ports.

**Comment by laviniat1996** [comment] 2022-11-28 05:00
Hi @Moka51 ,

It's been quite a while since we heard from you. Is this issue still present?

**Comment by DarianShawn** [comment] 2022-12-02 09:27
@laviniat1996 @zivkovicmilos 
I guess it is caused by the stuck channel in `notifyNewStatusEvent`. 
The node bypass the channel it received, but it hang on there in fact, and then no more events arrived.

We're trying to migrate the v0.2 `Syncer` protocol to Dogechain nodes. It happened, too.

**Comment by laviniat1996** [comment] 2022-12-06 08:57
Hi @DarianShawn , are you part of the same team as the user who reported this or are you running another project? If so, please provide more details about your issue. Thank you.

**Comment by DarianShawn** [comment] 2022-12-06 09:08
> Hi @DarianShawn , are you part of the same team as the user who reported this or are you running another project? If so, please provide more details about your issue. Thank you.

Nope, we are another project folk from your incredible work. [Dogechain](https://github.com/dogechain-lab/dogechain)
Zivkov knew it since we've been connected several times.
Some new features are developed and some merged from your repo.
And sometimes we report some serious bugs we found so that PolygonEdge upstream repo could fix it, too.

The `/syncer/v2` protocol is great, but some little flaws founded when we tried to migrate it.
The channel will be blocked and hang the remote peer notification if a new joint peer (sycner) start from Genesis.
It shall be easy to reproduce.

**Comment by laviniat1996** [comment] 2022-12-07 10:51
@DarianShawn I see that the user whom created this issue didn't reply back. Therefore, I will close this soon.
But I would like to invite you to open a new issue if you feel there's need, and report there all the problems you encountere with details. Thank you very much 🙏

**Comment by laviniat1996** [comment] 2022-12-12 09:46
Closing due to innactivity.

**Closed as completed by laviniat1996** 2022-12-12 09:46 UTC
