### ISSUE TITLE
Steady memory creep 

### ISSUE THREAD

**Issue by mrwillis** [0xPolygon/polygon-edge#653] opened 2022-07-25 19:32 UTC
### Description

It looks like there is still a memory creep issue present in the latest version of edge. Over a week, we can observe memory steadily increasing.

### Your environment

* OS and version Ubuntu 20 
* version of the Polygon Edge `0.4.1`
* branch that causes this issue `develop`

### Steps to reproduce

* Tell us how to reproduce this issue <br />
Create a new chain, run a node on an EC2 box on AWS for example. Observe memory increasing steadily over a week. 
* Where the issue is, if you know <br />
* Which commands triggered the issue, if any

### Expected behaviour

Memory should not be increasing

### Actual behaviour

Memory steadily increases over a 7 day period

### Logs

![image](https://user-images.githubusercontent.com/2652683/180858758-2a57f2a9-dcc0-4704-af15-fd92deb5ef53.png)

**Comment by akshar** [comment] 2022-07-25 20:02
Additional data:

[validator-prof-files.zip](https://github.com/0xPolygon/polygon-edge/files/9184431/validator-prof-files.zip)

**Comment by zivkovicmilos** [comment] 2022-07-29 14:30
Hey @mrwillis,

Thank you for opening up the issue 🙏 

We've set up detailed memory monitoring to figure out where the creep is coming from.

Letting you know as soon as we have more info

**Comment by zivkovicmilos** [comment] 2022-08-01 12:27
Hey @mrwillis,

Just an update regarding this, we've spun up a cluster and let it run for a couple of days while monitoring memory usage.

<img width="1582" alt="Screenshot 2022-08-01 at 14 25 45" src="https://user-images.githubusercontent.com/16712663/182147460-a8adfc08-7548-4629-bead-0a8a1520a98a.png">

Looks like we have some memory leaks within helper methods, we're still looking into it, just letting you know we've confirmed it 🙏

**Comment by SwaroopH** [comment] 2022-08-19 03:54
Looks like we are seeing even larger memory leaks with #668 

Also, a dedicated RPC node (not a validator) ran out of memory much faster. Didn't observe this with previous release.

**Comment by zivkovicmilos** [comment] 2022-08-19 08:03
@SwaroopH,

Can you please post the prof files you are seeing?

What version of Edge are you running on?

**Comment by SwaroopH** [comment] 2022-08-21 17:21
> prof

Is there a flag to generate it?

**Comment by dankostiuk** [comment] 2022-08-22 14:27
Hey @zivkovicmilos , the issue appears to still exist for us as well for version `v0.5.0 develop @ fb219b`

I've used pprof on a validator node targeted by an instance of blockscout on our testnet to obtain a before (taken the morning of Aug 19) which can be compared to an after (taken just now).  

You can see around 20% creep since Friday:
![Screen Shot 2022-08-22 at 10 11 27 AM](https://user-images.githubusercontent.com/3344880/185944416-2bd97c07-82f8-4a1a-a482-713b7f6b37aa.png)

Could it be that you only added the pprof lib within jsonrpc.go instead of main.go? Therefore you may have missed any memory creep resulting from another service outside of the jsonrpc layer...

Attached both pprof files and svg outputs here:
[Archive.zip](https://github.com/0xPolygon/polygon-edge/files/9395162/Archive.zip)

**Comment by zivkovicmilos** [comment] 2022-08-22 14:30
@dankostiuk 

Well this is not worrying at all 🙃 

Reopening this issue to look into it as a top priority. Thank you for the notification as always 🙏

**Comment by zivkovicmilos** [comment] 2022-08-23 12:48
Hey @dankostiuk,

I've finally managed to locate the source of the problem - [we are keeping a reference to an object that is a linked list](https://github.com/0xPolygon/polygon-edge/blob/de628407602342f1bfc0174c9f6671edca363cdd/consensus/ibft/ibft.go#L356), that [never releases memory when new blocks come in](https://github.com/0xPolygon/polygon-edge/blob/de628407602342f1bfc0174c9f6671edca363cdd/blockchain/subscription.go#L215-L217). This is something that is present for a long, long time in Edge (Polygon SDK days 🙂 ), you would see the same memory leak if you started an old Edge cluster (pre IBFT 2.0) and left the `monitor` command running.

We are currently working on completely refactoring this event subscription trash into a working module.
I will keep you posted here on the progress, and apologize on behalf of the dev team that some legacy code like this is still around and causing problems 🙏

**Comment by ivanbozic21** [comment] 2022-09-26 14:06
Hi @mrwillis 

We wish to let you know that this memory issue is resolved with our latest Polygon Edge 0.5.1 release.

If there will be any further problems, then feel free to re-open this request.

**Closed as completed by ivanbozic21** 2022-09-26 14:06 UTC
Labels: bug, in the pipeline
