### ISSUE TITLE
Peer count doesn't fully recover after network partition

### ISSUE THREAD

**Issue by mrwillis** [0xPolygon/polygon-edge#309] opened 2021-12-22 16:47 UTC
### Description

We've noticed an issue where if we kill connectivity (specifically outbound connectivity) to a node, in some cases it does not fully recover to the total peer count

### Your environment

* OS and version Ubuntu 20
* version of the Polygon SDK `develop`
* branch that causes this issue `develop`

### Steps to reproduce

* Tell us how to reproduce this issue 
Create a 4 node cluster (all bootnodes). Randomly kill connectivity with the nodes and restore them after some time. Simplest way is to make a 4 node cloud cluster and just toggle the security groups for outbound on AWS for example. You can try some variant of this script in node:

```typescript
import EC2 from "aws-sdk/clients/ec2";

function randomIntFromInterval(min: number, max: number) {
  // min and max included
  return Math.floor(Math.random() * (max - min + 1) + min);
}

function notEmpty<TValue>(value: TValue | null | undefined): value is TValue {
  return value !== null && value !== undefined;
}

const fullyConnectedGroups = [
  "sg-a",
  "sg-b",
  "sg-c",
];
const disconnectedGroups = ["sg-a", "sg-b"];
// You can set the fullyConnectedGroups to be the security groups required for fully connected nodes, i.e., all nodes can community (full inbound/full outbound)
// You can set disconnectedGroups to be a subset (or an empty set) of the fullyConnected groups, for example, remove the one that allows for outbound access (sg-c in this case) 

export async function main() {
  const ec2 = new EC2({ region: "us-east-1" });
  var params = {
    Filters: [
      {
        Name: "tag:network",
        Values: ["toronto"],
      },
    ],
  };
  const instances = await ec2.describeInstances(params).promise();
  const instanceIds = instances
    .Reservations!.map((reservation) =>
      reservation.Instances!.map((instance) => instance.InstanceId)
    )
    .flat();
  console.log(`Instance IDs ${instanceIds}`);
  const nonEmptyIds = instanceIds.filter((id) => id !== undefined);
  while (true) {
    // Shuffle array
    const shuffled = nonEmptyIds.sort(() => 0.5 - Math.random());

    // Get sub-array of first n elements after shuffled
    let selectedIds = shuffled
      .slice(0, randomIntFromInterval(0, instanceIds.length))
      .filter(notEmpty);
    console.log("Selected IDs to disconnect ", selectedIds);
    for (const id of selectedIds) {
      console.log(`Disconnecting ${id}`);
      await ec2
        .modifyInstanceAttribute({ InstanceId: id, Groups: disconnectedGroups })
        .promise();
    }
    const reconnectWaitTime = randomIntFromInterval(30, 60);
    console.log(`Waiting ${reconnectWaitTime} seconds to reconnect nodes`);
    // Wait random amount of time from 30 to 60s to reconnect
    await new Promise((r) => setTimeout(r, reconnectWaitTime * 1000));
    for (const id of selectedIds) {
      console.log(`Reconnecting ${id}`);
      await ec2
        .modifyInstanceAttribute({
          InstanceId: id,
          Groups: fullyConnectedGroups,
        })
        .promise();
    }
    const continueWaitTime = randomIntFromInterval(1, 20);
    console.log(`Waiting ${continueWaitTime} seconds to continue`);
    await new Promise((r) => setTimeout(r, continueWaitTime * 1000));
  }
}

main().then(() => console.log("Done"));

```

* Where the issue is, if you know <br />
* Which commands triggered the issue, if any

### Expected behaviour

Nodes should recover to the total peer count 

### Actual behaviour

Nodes only recover to a fraction of the total peers

### Logs

See our Grafana screenshot with the new metrics from 

https://github.com/0xPolygon/polygon-sdk/pull/302

You can see the behaviour prior to the script starting, and then afterwards when connectivity is restored. This was a 4 validator node cluster with 2 additional, non-sealing nodes online. Full connectivity was restored at 11:02

![image](https://user-images.githubusercontent.com/2652683/147121730-4e5fca02-1ee9-4f2c-8238-f5e3209fef00.png)

Here is another example with the 4 validator nodes and the additional 2 non-sealing nodes offline. Full connectivity was restored at 12:15:

![image](https://user-images.githubusercontent.com/2652683/147131212-f54dcc90-ec97-440e-8be0-4ed2b6888c72.png)

In general it looks like these 2 errors come as a pair for each node:

```
[ERROR] polygon.network: failed to dial bootnode: id=16Uiu2HAmP2bpgr3sLUUzt61bEzAL7ptdNXnvsfnwcxyrfCMFjxDf err="rpc error: code = Unavailable desc = error reading from server: stream reset"

[ERROR] polygon.consensus.syncer: failed to notify: err="rpc error: code = Unavailable desc = error reading from server: stream reset"
```

### Proposed solution

If you have an idea of how to fix this issue, please write it down here, so we can begin discussing it

**Comment by Kourin1996** [comment] 2021-12-28 08:46
Hello, @mrwillis. Thank you for raising the issue. I could reproduce this issue with docker.  Basically, this issue can be divided into 2 issues:

(1) Node can't reconnect to a peer if node failed to connect to the peer before. It's caused because peer will not be removed from routing table when node failed to connect. For that reason, node can't catch NewPeer event from routing table when node add peer info into routing table next time.

(2) Node won't connect to more bootnode once the node connects to one peer. The recovery process will happen and try to connect to one bootnode only when node doesn't connect to any peer. Let's say we have 4 bootnodes. And we let them connect to no peers firstly and fix the network issue after that. If A and B dial each other while C and D dials each other, we will have 2 sub-networks. In this case, each peer will not connect to new peer because they're connecting to one peer at least and recovery process doesn't happen.

![Untitled-2021-12-27-1109](https://user-images.githubusercontent.com/19720977/147577169-f537a73d-f44a-49a1-9be3-ee526c378ed3.png)

I fixed (1) at https://github.com/0xPolygon/polygon-sdk/pull/318 and (2) will be fixed at another PR.

**Comment by zivkovicmilos** [comment] 2022-01-14 15:17
Hey @mrwillis,

Just wanted to give you a heads up that the 2nd PR @Kourin1996 mentioned is up now, so I'll link it 👍 

PR #343

**Closed as completed** 2022-03-31 14:58 UTC
Labels: bug
