### ISSUE TITLE
Metamask transaction Error

### ISSUE THREAD

**Issue by polygomic** [0xPolygon/polygon-edge#1693] opened 2023-07-02 00:04 UTC
metamask can not add on firefox but on chrome we can add bit when try to send transaction in version 1.0.0 I got  :
Failed transaction
Transaction 0 failed! [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32600,"message":"invalid tx type"}}}' 

## Your environment
- OS and version.
- The version of the Polygon Edge.    
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider).
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.).

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm?

## Expected behavior
- Tell us what should happen.
- Tell us what happened instead.

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by polygomic** [comment] 2023-07-24 02:28
this will always happens when we use estimated gas version og polygon-edge

**Comment by Stefan-Ethernal** [comment] 2023-08-17 09:35
The problem is most likely that London hard fork is not enabled. This comment contains an explanation of how to enable it: https://github.com/0xPolygon/polygon-edge/issues/1743#issuecomment-1663479312

**Comment by dusan-maksimovic** [comment] 2023-09-14 08:19
This problem should be fixed by [this](https://github.com/0xPolygon/polygon-edge/pull/1805) PR.

**Comment by Stefan-Ethernal** [comment] 2023-09-15 14:18
Marking as fixed per https://github.com/0xPolygon/polygon-edge/issues/1693#issuecomment-1718983375.

**Closed as completed by Stefan-Ethernal** 2023-09-15 14:18 UTC
