### ISSUE TITLE
big amount in Metamask wallet makes problem

### ISSUE THREAD

**Issue by fastepic** [0xPolygon/polygon-edge#54] opened 2021-06-05 12:00 UTC
## [Subject of the issue]
Big value in premine genesis .... 0x115EEC47F6CF7E35000000  (21000000 whole number in Metamask )

### Description

After creation new network with premine amount like above in address it give big number in Metamask connected by rpc to network. When made real transaction from Metamask ( small value like 1 or 5  ) it is still pending. Not this problem if starting amount on account is default ( 1000 ). 

### Your environment

* OS and version - Ubuntu Fossa
* version of the Polygon SDK develop today
* branch that causes this issue

### Steps to reproduce
like above 

If you have an idea of how to fix this issue, please write it down here, so we can begin discussing it
Maybe too big value from Metamask this starting point and problems with number in javascript?

**Comment by zivkovicmilos** [comment] 2021-06-08 09:45
Hey @fastepic,

Thank you for reaching out.

We've tried to replicate this bug, and concluded that the issue is probably a formatting problem on Metamask.
Spinning up a Ganache instance without setting the symbol produces the same problem.

The interesting thing is - if you set the symbol to be a blank space (` `) on Metamask, the balance renders fine. This is probably due to the fact that [they're not handling this catch branch](https://github.com/MetaMask/controllers/blob/82386c490d6eb4c15c449d7c5ed3c53f94060497/src/assets/CurrencyRateController.ts#L222) correctly.

So the solution, not just for Polygon SDK, but for any custom RPC is to set the `Symbol` field to anything in Metamask, even if it says it's optional.

I'm closing this issue since it's not something that needs solving on our side, but we'll try to raise an issue on the Metamask repo that is causing this bug.

**Closed as completed by zivkovicmilos** 2021-06-08 09:45 UTC
