### ISSUE TITLE
Recurring `Unable to process flush` WS error messages on premature client exit

### ISSUE THREAD

**Issue by dankostiuk** [0xPolygon/polygon-edge#486] opened 2022-04-01 21:58 UTC
### Description

If fixed this would definitely help to minimize unnecessary error logs.

When a node has an open web-socket connection to a client that exits prematurely, we see the the recurring errors below that spam our logs until we perform a restart:

```
2022-04-01T21:30:38.017Z [ERROR] polygon.filter: Unable to process flush, writev tcp 555.555.555.555:10002->555.555.555.555:38176: use of closed network connection
```

### Your environment

* OS and version `Ubuntu 20`
* version of the Polygon Edge `v0.3.2`
* branch that causes this issue `develop`

### Steps to reproduce

1. Connect a client directly to a node + subscribe to a WS connected (e.g. Blockscout explorer)
2. Terminate the client process 
3. Observe recurring `Unable to process flush` on the host node 

### Expected behaviour

I would only expect an initial error indicating an issue with the WS connection, rather than seeing the same error persist requiring a node restart.

### Actual behaviour

The same error persists requiring a node restart.

### Logs

See above.

### Proposed solution

Perhaps after the same WS filter has been attempted to be flushed 5 times - if we still encounter errors on flushing, we should simply discard this filter from the FileManager.

**Comment by Kourin1996** [comment] 2022-04-03 18:14
@dankostiuk Hello, Thank you for raising the issue! I could reproduce this error locally and identify the reason. I create PR #487. Please wait for the PR to be merged. I appreciate your help.

**Closed as completed** 2022-04-20 14:06 UTC
Labels: bug
