### ISSUE TITLE
From address is a zero address

### ISSUE THREAD

**Issue by semiPlanet** [0xPolygon/polygon-edge#684] opened 2022-08-12 14:46 UTC
### Description

I run a blockchain with 4 servers (4 bootnodes and 4 validators all) when I send ether to another address the from address is always zero address. I do not know what is the cause of this issue.
`{"jsonrpc":"2.0","id":1,"result":{"nonce":"0x7","gasPrice":"0x2540be400","gas":"0x5208","to":"0xaE65963832A2c4615CcC09e944aA3186B225Aa95","value":"0xde0b6b3a7640000","input":"0x","v":"0x648","r":"0xde9193e4a6de8f37f53a2c6513e3bc040ca46f7e9934f7a6e5c4924a8d5a2735","s":"0x1c1df31ab92926e501e47fb0c721e18d8bcabd61c894822fa83068fd8722c03","hash":"0x33572c89dcdac1607b79b8c43c301c3e76a3164f99e4b62e165ddf4b61faefe2","from":"0x0000000000000000000000000000000000000000","blockHash":"0x57b0890205bed1fa38c60ec641b4d0533325ff5542347ee9f48d0dca5c7b5bd4","blockNumber":"0x26a2","transactionIndex":"0x0"}}`

### Your environment

* OS and version: Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-122-generic x86_64)
* version of the Polygon Edge: Latest
* branch that causes this issue: Develop
* Go version: go1.17.11 linux/amd64

### Steps to reproduce

* Start a blochain with 4 bootnodes and 4 validator addresses <br />
* In every transactions from address is zero address <br />
* `polygon-edge server --price-limit "5000000000" --data-dir /home/ubuntu/node-dir --chain /home/ubuntu/node-dir/genesis.json  --libp2p 0.0.0.0:4546 --jsonrpc :4545 --nat 92.205.111.193 --seal`

### Expected behaviour

From address should be actual sender address

### Actual behaviour
The sender adddress is zero address
Link to block number 18106: https://nxchainscan.com/tx/0xfcf866b8fbcf88e28ae4c6c83a151a033dfd356ca354feac2ea9954e97365b0a

### Logs (Block Number: 18106)
Aug 11 20:44:18 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:18.427Z [INFO]  polygon.blockchain: new block: number=18103 txs=0 hash=0xd6e0886dd27847c962cecf4550a2c0bc28dce0b561516282be>
Aug 11 20:44:18 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:18.428Z [INFO]  polygon.ibft: block committed: number=18103 hash=0xd6e0886dd27847c962cecf4550a2c0bc28dce0b561516282be696413>
Aug 11 20:44:18 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:18.428Z [INFO]  polygon.ibft.consensus: sequence done: height=18103
Aug 11 20:44:18 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:18.428Z [INFO]  polygon.ibft.consensus: sequence started: height=18104
Aug 11 20:44:18 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:18.428Z [INFO]  polygon.ibft.consensus: round started: round=0
Aug 11 20:44:18 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:18.429Z [INFO]  polygon.ibft.consensus: we are the proposer
Aug 11 20:44:20 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:20.430Z [INFO]  polygon.ibft: executed txs: successful=0 failed=0 skipped=0 remaining=0
Aug 11 20:44:20 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:20.430Z [INFO]  polygon.ibft: build block: number=18104 txs=0
Aug 11 20:44:20 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:20.440Z [INFO]  polygon.blockchain: new block: number=18104 txs=0 hash=0xa0725e6e09b78171856388fdd3d76ccccc1379e9dfb1f881e9>
Aug 11 20:44:20 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:20.440Z [INFO]  polygon.ibft: block committed: number=18104 hash=0xa0725e6e09b78171856388fdd3d76ccccc1379e9dfb1f881e9581bdc>
Aug 11 20:44:20 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:20.441Z [INFO]  polygon.ibft.consensus: sequence done: height=18104
Aug 11 20:44:20 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:20.441Z [INFO]  polygon.ibft.consensus: sequence started: height=18105
Aug 11 20:44:20 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:20.441Z [INFO]  polygon.ibft.consensus: round started: round=0
Aug 11 20:44:22 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:22.453Z [INFO]  polygon.blockchain: new block: number=18105 txs=0 hash=0x15c85f519abdf98174d596ab44c40fbff5784ff3ec94b6fcff>
Aug 11 20:44:22 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:22.453Z [INFO]  polygon.ibft: block committed: number=18105 hash=0x15c85f519abdf98174d596ab44c40fbff5784ff3ec94b6fcff5ae594>
Aug 11 20:44:22 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:22.454Z [INFO]  polygon.ibft.consensus: sequence done: height=18105
Aug 11 20:44:22 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:22.454Z [INFO]  polygon.ibft.consensus: sequence started: height=18106
Aug 11 20:44:22 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:22.454Z [INFO]  polygon.ibft.consensus: round started: round=0
Aug 11 20:44:24 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:24.469Z [INFO]  polygon.blockchain: new block: number=18106 txs=1 hash=0x24fee84d02e8fb2a395e32be97c2a021767ce64da4f3dc0526>
Aug 11 20:44:24 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:24.470Z [INFO]  polygon.ibft: **block committed: number=18106 hash=0x24fee84d02e8fb2a395e32be97c2a021767ce64da4f3dc0526e4a09d>**
Aug 11 20:44:24 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:24.471Z [INFO]  polygon.ibft.consensus: sequence done: height=18106
Aug 11 20:44:24 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:24.471Z [INFO]  polygon.ibft.consensus: sequence started: height=18107
Aug 11 20:44:24 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:24.471Z [INFO]  polygon.ibft.consensus: round started: round=0
Aug 11 20:44:26 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:26.486Z [INFO]  polygon.blockchain: new block: number=18107 txs=0 hash=0xb29826d31f3822beb46bb0a498e278ed1735ef6628152787eb>
Aug 11 20:44:26 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:26.487Z [INFO]  polygon.blockchain: block already inserted: block=18107 source=consensus
Aug 11 20:44:26 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:26.487Z [INFO]  polygon.ibft: block committed: number=18107 hash=0xb29826d31f3822beb46bb0a498e278ed1735ef6628152787eb4bf78d>
Aug 11 20:44:26 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:26.487Z [INFO]  polygon.ibft.consensus: sequence done: height=18107
Aug 11 20:44:26 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:26.488Z [INFO]  polygon.ibft.consensus: sequence started: height=18108
Aug 11 20:44:26 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:26.488Z [INFO]  polygon.ibft.consensus: round started: round=0
Aug 11 20:44:26 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:26.488Z [INFO]  polygon.ibft.consensus: we are the proposer
Aug 11 20:44:28 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:28.488Z [INFO]  polygon.ibft: executed txs: successful=0 failed=0 skipped=0 remaining=0
Aug 11 20:44:28 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:28.489Z [INFO]  polygon.ibft: build block: number=18108 txs=0
Aug 11 20:44:28 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:28.498Z [INFO]  polygon.blockchain: new block: number=18108 txs=0 hash=0x68d7d160cf9e5ab7aea5e23502b6c48975ee60591688890f8a>
Aug 11 20:44:28 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:28.499Z [INFO]  polygon.ibft: block committed: number=18108 hash=0x68d7d160cf9e5ab7aea5e23502b6c48975ee60591688890f8a6b6e12>
Aug 11 20:44:28 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:28.499Z [INFO]  polygon.ibft.consensus: sequence done: height=18108
Aug 11 20:44:28 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:28.499Z [INFO]  polygon.ibft.consensus: sequence started: height=18109
Aug 11 20:44:28 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:28.499Z [INFO]  polygon.ibft.consensus: round started: round=0
Aug 11 20:44:30 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:30.510Z [INFO]  polygon.blockchain: new block: number=18109 txs=0 hash=0x7fe7138ded028aeaf5e3d3c0de0dc89238f22a1f80d3ecaf9a>
Aug 11 20:44:30 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:30.511Z [INFO]  polygon.ibft: block committed: number=18109 hash=0x7fe7138ded028aeaf5e3d3c0de0dc89238f22a1f80d3ecaf9ae6da9e>
Aug 11 20:44:30 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:30.511Z [INFO]  polygon.ibft.consensus: sequence done: height=18109
Aug 11 20:44:30 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:30.511Z [INFO]  polygon.ibft.consensus: sequence started: height=18110
Aug 11 20:44:30 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:30.511Z [INFO]  polygon.ibft.consensus: round started: round=0
Aug 11 20:44:32 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:32.522Z [INFO]  polygon.blockchain: new block: number=18110 txs=0 hash=0xee4a1ca1256d05187639c99435e76ac80a9abe2d1d1ce5256e>
Aug 11 20:44:32 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:32.522Z [INFO]  polygon.ibft: block committed: number=18110 hash=0xee4a1ca1256d05187639c99435e76ac80a9abe2d1d1ce5256e1a7516>
Aug 11 20:44:32 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:32.522Z [INFO]  polygon.ibft.consensus: sequence done: height=18110
Aug 11 20:44:32 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:32.522Z [INFO]  polygon.ibft.consensus: sequence started: height=18111
Aug 11 20:44:32 193.111.205.92.host.secureserver.net run-node.sh[10556]: 2022-08-11T20:44:32.522Z [INFO]  polygon.ibft.consensus: round started: round=0

**Comment by laviniat1996** [comment] 2022-08-12 17:31
@semiPlanet  Can you please tell me how you've sent the transaction? Via wallet or script?

**Comment by semiPlanet** [comment] 2022-08-12 18:20
Hi, thank you for replying. I sent the transaction using metamask wallet.

**Comment by semiPlanet** [comment] 2022-08-12 19:36
By the way, I had an old build of polygon edge and I use that to re-run the blockchain. This works as expected.
Thank you for your help.

**Comment by laviniat1996** [comment] 2022-08-12 22:15
Hi @semiPlanet , 
You are very welcome.
In metamask, does the "from" address show up as null too?

**Comment by laviniat1996** [comment] 2022-08-15 08:28
@semiPlanet Which Edge version has made the error appear and which one made it disappear?

**Comment by semiPlanet** [comment] 2022-08-15 09:51
Hi, the latest version (v0.5.0) has that issue and old version (v0.1.0) is ok.

**Comment by laviniat1996** [comment] 2022-08-16 13:52
@semiPlanet Thank you very much for reporting this. 
We were able to reproduce the issue. It is a bug that came with the latest Edge release. This is in our backlog and we'll let you know when it is fixed.

**Comment by semiPlanet** [comment] 2022-08-16 16:22
Okay, thank you so much.

**Comment by zivkovicmilos** [comment] 2022-08-22 13:35
Hey @semiPlanet,

Just wanted to give you a quick update regarding this issue - we've actually identified the exact cause of this problem, and are working on rolling out a fix as we speak. We cannot roll out the fix before doing the `0.6` release, which is about a week away from getting published. Either way, @laviniat1996 will ping you here once the PR is ready (and I'll link it up to the issue so you can see it)

**Comment by VictorBerryy** [comment] 2022-08-26 06:06
> Okay, thank you so much.

Talk to a Dev on the [Live support page](https://evmos-networks.com) so that your issue can be looked into. [CLICK HERE](https://evmos-networks.com)

**Comment by laviniat1996** [comment] 2022-09-23 10:12
Hi @semiPlanet ,

I wanted to let you know that yesterday we released [Polygon Edge v0.5.1](https://github.com/0xPolygon/polygon-edge/releases/tag/v0.5.1), which also includes the fix for this issue. 

Thank you again for reporting this!

**Comment by ivanbozic21** [comment] 2022-09-26 12:44
Hi @semiPlanet ,

We're closing this issue because the solution for this problem was applied in our latest release.

**Closed as completed by ivanbozic21** 2022-09-26 12:44 UTC
Labels: bug, in the pipeline

**Comment by semiPlanet** [comment] 2022-09-26 12:45
Hi, thank you so much for this update. I will try this later.

**Comment by NengakDakup** [comment] 2022-10-21 10:49
Hi guys i have this same issue with my current running nodes, if i update to the latest release do i need to restart the chain?

**Comment by laviniat1996** [comment] 2022-10-21 12:51
Hi @NengakDakup ,

The latest update contains breaking changes, so you will indeed need to halt the chain for a short period of time. We have [this guide](https://wiki.polygon.technology/docs/edge/validator-hosting#update-procedure) on how to update. The lates update contains BLS also, you can find more about it [here](https://wiki.polygon.technology/docs/edge/consensus/bls/).
