### ISSUE TITLE
Txpool pending and queued sets are never pruned, causing eventual overflow or DOS

### ISSUE THREAD

**Issue by mrwillis** [0xPolygon/polygon-edge#226] opened 2021-11-18 23:40 UTC
### Description

There is no mechanism to reduce transactions that might be eventually valid from the pending or queued sets, causing perpetual growth. 

### Your environment

* OS and version Ubuntu 20
* version of the Polygon SDK 6efebc6a92f885082620ed2a8d59e37d4d27074c
* branch that causes this issue `develop`

### Steps to reproduce

* Tell us how to reproduce this issue <br />
Create a chain with 4 validators. Create an a premine with a balance of 100 ETH. Submit txns with nonce 0...1000 and submit **them immediately without waiting for receipt**, each sending 1 ETH to some random account. Observe the first ~100 transactions get mined. Now the txn pool `pendingQueue` should contain 900 transactions.

These 900 transactions will constantly be popped then re-pushed back onto the queue because they are thrown with a recoverable error which pushes them back onto the queue

https://github.com/0xPolygon/polygon-sdk/blob/6efebc6a92f885082620ed2a8d59e37d4d27074c/consensus/ibft/ibft.go#L406

```
2021-11-18T16:24:28.038-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
```

* Where the issue is, if you know <br />

* Which commands triggered the issue, if any

`./main server`

### Expected behaviour

Transactions that are invalid for a long time should eventually be dropped. 

### Actual behaviour

Transactions that are invalid are constantly re-pushed onto the queue as most of the errors thrown here are recoverable

https://github.com/0xPolygon/polygon-sdk/blob/6efebc6a92f885082620ed2a8d59e37d4d27074c/state/executor.go#L358

### Logs

`txpool_status` on our testnet validator nodes

```
{ jsonrpc: '2.0', id: null, result: { pending: 0, queued: 1 } }
{ jsonrpc: '2.0', id: null, result: { pending: 0, queued: 42 } }
{ jsonrpc: '2.0', id: null, result: { pending: 0, queued: 329 } }
{ jsonrpc: '2.0', id: null, result: { pending: 3292, queued: 1561 } }
{ jsonrpc: '2.0', id: null, result: { pending: 3968, queued: 22 } }
{ jsonrpc: '2.0', id: null, result: { pending: 1145, queued: 14379 } }
{ jsonrpc: '2.0', id: null, result: { pending: 69, queued: 5711 } }
{ jsonrpc: '2.0', id: null, result: { pending: 109, queued: 5629 } }
{ jsonrpc: '2.0', id: null, result: { pending: 256, queued: 5559 } }
{ jsonrpc: '2.0', id: null, result: { pending: 0, queued: 42 } }
{ jsonrpc: '2.0', id: null, result: { pending: 60, queued: 5736 } }
{ jsonrpc: '2.0', id: null, result: { pending: 3706, queued: 1641 } }
{ jsonrpc: '2.0', id: null, result: { pending: 3630, queued: 1389 } }
{ jsonrpc: '2.0', id: null, result: { pending: 0, queued: 204 } }
```

```
2021-11-18T16:23:40.026-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:23:48.026-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:23:56.022-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:24:04.025-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:24:12.027-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:24:20.027-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:24:20.027-0500 [INFO]  polygon.consensus.ibft: picked out txns from pool: num=0 remaining=985
2021-11-18T16:24:28.038-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:24:28.038-0500 [INFO]  polygon.consensus.ibft: picked out txns from pool: num=0 remaining=985
2021-11-18T16:24:36.024-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:24:36.024-0500 [INFO]  polygon.consensus.ibft: picked out txns from pool: num=0 remaining=985
2021-11-18T16:24:44.028-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:24:52.026-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:25:00.025-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:25:00.025-0500 [INFO]  polygon.consensus.ibft: picked out txns from pool: num=0 remaining=985
2021-11-18T16:25:08.024-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:25:08.024-0500 [INFO]  polygon.consensus.ibft: picked out txns from pool: num=0 remaining=985
2021-11-18T16:25:16.023-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
```

Please paste any logs here that demonstrate the issue, if they exist

### Proposed solution

There should be some sort of periodic pool pruning as in geth. Geth has a periodic mechanism:

https://github.com/maticnetwork/bor/blob/a9c71eff578c652ddfe00a73267454bed5957ed0/core/tx_pool.go#L1137

And the algorithms:

https://github.com/maticnetwork/bor/blob/a9c71eff578c652ddfe00a73267454bed5957ed0/core/tx_pool.go#L1377
https://github.com/maticnetwork/bor/blob/a9c71eff578c652ddfe00a73267454bed5957ed0/core/tx_pool.go#L1462

**Comment by Kourin1996** [comment] 2021-11-24 09:12
@mrwillis Hello, Thanks for raising the issue. I have one question. You described you sent 1000 transactions to node. But txpool_status returns that pending is 3968 from some node. Is it caused by the same scenario you described above?

**Comment by mrwillis** [comment] 2021-11-24 18:26
@Kourin1996 sorry yes, I just did the 1000 as an example. The logs are caused by the same scenario just more txns.

**Comment by Kourin1996** [comment] 2021-12-20 09:24
@mrwillis Hello, sorry that I couldn't share any updates. I had opened the PR to solve this issue. but as you can see, there is TxPool refactor ongoing in https://github.com/0xPolygon/polygon-sdk/pull/287. A similar feature would be added after this refactor is merged. I will keep this issue open. Thank you.

**Closed as completed** 2022-05-11 12:22 UTC
Labels: bug
