### ISSUE TITLE
New node `fail to write block` error when syncing near most recent block

### ISSUE THREAD

**Issue by dankostiuk** [0xPolygon/polygon-edge#169] opened 2021-09-29 15:43 UTC
### Description

When a new peer is syncing, it looks like after the last batch sync of blocks, we sometimes get a failure:
```
`[ERROR] polygon.consensus.syncer: failed to write block: err="parent of 0x5dda26ea7e3157baa4fa07746be00c43c2f084a946a2fb171634650f34efbc27 (853608) not found: 0xc2cbd6ac4ed7b7c340f6070bc2e13caef6ec582e14acffca41f49f9ae50760c9"`
```

See larger log snippet:
```
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.442Z [INFO]  polygon.blockchain: write blocks: num=10 from=852347 to=852356 parent=0xcb750c6af46655acc5d8a2ef0ff555da7cace894c761da985a99a3d3862dbeb5
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.479Z [INFO]  polygon.blockchain: new block: number=852347 hash=0x12039ac1d933d9a0c4761ae84ecbb227a7e8232b2b590d0b90965037e6e9fe51 txns=0 generation_time_in_sec=2
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.480Z [INFO]  polygon.blockchain: new block: number=852348 hash=0xe550e56c73dd0695a218cb509e993b18a0c7229e0a6923b2caee328c76b60029 txns=0 generation_time_in_sec=2
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.482Z [INFO]  polygon.blockchain: new block: number=852349 hash=0xd1464576099a359200620cfa5e8c468b8efa61affe8843fef3260528a4b9f2c8 txns=0 generation_time_in_sec=2
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.482Z [INFO]  polygon.blockchain: new block: number=852350 hash=0x36c9b9114dd72fa7c3d6c6c7d78910e2acec6a038e9860c1571ea1592b072e2a txns=0 generation_time_in_sec=10
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.483Z [INFO]  polygon.blockchain: new block: number=852351 hash=0xf1f1e6c70bf3caedb625e2087b5c1df5075bd1550c6cd2c7e914462e9479933e txns=0 generation_time_in_sec=2
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.485Z [INFO]  polygon.blockchain: new block: number=852352 hash=0x2a0f4cef8616c30d40d9dcaa9d421e31545fac74d047b758ae95fe07861714f5 txns=0 generation_time_in_sec=2
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.486Z [INFO]  polygon.blockchain: new block: number=852353 hash=0x7d0b63698c309d5aab3f28d64bd0cd30ce73356c003151509ca9585b03a3c346 txns=0 generation_time_in_sec=2
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.486Z [INFO]  polygon.blockchain: new block: number=852354 hash=0x1d83f22145427ccf4861da7ebfc5374ebd03ffd004e28f42669e5ba63b481e99 txns=1 generation_time_in_sec=10
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.489Z [INFO]  polygon.blockchain: new block: number=852355 hash=0x2d3147d271012dd927da8d0fc41f9c421594abe9a86c62ddd147fbbcc61f236e txns=0 generation_time_in_sec=2
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.490Z [INFO]  polygon.blockchain: new block: number=852356 hash=0x264a473677e736779edb91cc4753b90cf368d04f85395ea913114583599ee7e8 txns=0 generation_time_in_sec=2
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.490Z [INFO]  polygon.blockchain: new head: hash=0x264a473677e736779edb91cc4753b90cf368d04f85395ea913114583599ee7e8 number=852356
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.492Z [INFO]  polygon.blockchain: write block: num=853608 parent=0xc2cbd6ac4ed7b7c340f6070bc2e13caef6ec582e14acffca41f49f9ae50760c9
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.496Z [ERROR] polygon.consensus.syncer: failed to write block: err="parent of 0x5dda26ea7e3157baa4fa07746be00c43c2f084a946a2fb171634650f34efbc27 (853608) not found: 0xc2cbd6ac4ed7b7c340f6070bc2e13caef6ec582e14acffca41f49f9ae50760c9"
```

Restarting the node fixes the issue.

### Your environment

* OS and version `Ubuntu 20`
* version of the Polygon SDK `96be904 `
* branch that causes this issue `develop`

### Steps to reproduce

1. Have 4-node validator set writing and validating new blocks
2. Connect 5th peer and observe `polygon.blockchain: new block` output that occurs during syncing
3. When almost synced to the current block, we see the error above

### Expected behaviour

There shouldn't be an error that requires us to restart the node.

### Actual behaviour

An error stops the node from further syncing, requiring a restart.

**Comment by Kourin1996** [comment] 2021-10-03 18:22
Hello, @dankostiuk. Thank you for raising this issue. Could I ask if node No.5 worked after this error? I want to see logs from the error. I guess node try to begin new sync process after node failed to sync a block.

**Comment by Kourin1996** [comment] 2021-10-03 19:31
Hello, @dankostiuk. Thank you for raising the issue. I figured out some reasons after some investigations.

1. Peer is notifying latest block number as difficult. This value is used to find best peer at begin of sync process. But difficulty and block number is different value usually. That's why node couldn't find best peer.
2. In sync process, (1) node pulls batch of blocks from peer and write to chain (bulk sync) and begins (2) to sync a block one by one after this. In (2), node use blocks node got by subscription but node has only 50 latest blocks. I suppose the causes are following:
   (1) There was a delay after bulk sync is done before normal sync begins. This is rare case but still can continue to work because new sync process will begin.
   (2) Bulk sync doesn't work well because node use old status of peer. I checked this one, and node uses the status which is updated only first time. So I made syncer use latest status everytime.

I've fixed in https://github.com/0xPolygon/polygon-sdk/pull/164 against all issues. So please wait until this PR is merged or you can try this branch. Thank you.

**Comment by dankostiuk** [comment] 2021-10-04 13:56
Thanks again @Kourin1996, as usual your help here is appreciated 👍

**Closed as completed** 2021-10-05 13:23 UTC
Labels: bug
