### ISSUE TITLE
Restart with failure for the last node

### ISSUE THREAD

**Issue by fastepic** [0xPolygon/polygon-edge#55] opened 2021-06-05 14:36 UTC
## [Subject of the issue]
Restarted like the last  client sever for doc example after stop all nodes. The three other without problem restarted.
go run main.go server --data-dir ./test-chain-4 --chain genesis.json --grpc :40000 --libp2p :40001 --jsonrpc :40002 --seal

### Description

2021-06-05T16:32:54.961+0200 [INFO]  polygon.jsonrpc: http server started: addr=127.0.0.1:40002
2021-06-05T16:32:54.961+0200 [INFO]  polygon.consensus.ibft: syncing past snapshots: from=0 to=4162
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc8ad97]

goroutine 1 [running]:
github.com/0xPolygon/minimal/consensus/ibft.(*Snapshot).Copy(0x0, 0x0)
	/home/robert/Documents/polygonsdk/polygon-sdk/consensus/ibft/snapshot.go:367 +0x37
github.com/

Describe your issue in as much detail as possible here

### Your environment

* OS and version
* version of the Polygon SDK
* branch that causes this issue

### Steps to reproduce

* Tell us how to reproduce this issue <br />
* Where the issue is, if you know <br />
* Which commands triggered the issue, if any

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Logs

Please paste any logs here that demonstrate the issue, if they exist

### Proposed solution

If you have an idea of how to fix this issue, please write it down here, so we can begin discussing it

**Comment by Kourin1996** [comment] 2021-06-10 08:39
Hello, @fastepic. I'm sorry I couldn't answer this issue sooner. I had been trying to reproduce the issue in my local environment.

I think it's rare case. The issue seems to happen when node failed to load snapshot for IBFT and has empty snapshots on initializing. You can produce this error easily by deleting `consensus/metadata` and `consensus/snapshots` in data-dir and starting node again. I'm not 100% sure the issue you faced are caused by same reason, but perhaps node couldn't store these data when you terminated a process on the first time.

I will fix corresponding code. Thank you for your report.

**Comment by fastepic** [comment] 2021-06-11 04:39
Thank you. It is possible that computer was in heavy work ( other processes ) when I test it so it can be correlate with your suggestion and was problem with storing data.

**Comment by Kourin1996** [comment] 2021-07-01 11:22
Hi, @fastepic. I've fixed the issue and the code has been merged into `develop` branch. I will close this issue for now. I'm sure this issue will no longer happen. But you can reopen this issue and continue discussion if you find related issue. Thanks.

**Closed as completed by Kourin1996** 2021-07-01 11:23 UTC
Labels: bug
