### ISSUE TITLE
Bootnode peer discovery fails

### ISSUE THREAD

**Issue by adaki2004** [0xPolygon/polygon-edge#1094] opened 2023-01-04 13:02 UTC
# Generated bootnode id seems to be mismatched with the actually to-be-discovered node id.
## Description
I am trying to build up a private network with docker compose.

For that I use a modified version of this repo's: 

- Dockerfile. (See mine attached. I had to rename to .txt bc it did not allowed me to upload)
- polygon-edge.sh (See mine attached. I had to rename to .txt bc it did not allowed me to upload)
- and docker-compose.yml (See mine attached. Only difference is that it uses (my local Docerfile, see dockerfile diffs in Dockerfile. Also .yml renamed to .txt)
[docker-compose.txt](https://github.com/0xPolygon/polygon-edge/files/10344268/docker-compose.txt)
[Dockerfile.txt](https://github.com/0xPolygon/polygon-edge/files/10344269/Dockerfile.txt)
[polygon-edge.txt](https://github.com/0xPolygon/polygon-edge/files/10344270/polygon-edge.txt)

When I attach to those nodes, all are complaining about this:

```
2023-01-04T12:23:34.835Z [ERROR] polygon.network.discovery: Unable to execute bootnode peer discovery: bootnode=16Uiu2HAkxgphSqizpEDUUWLospTg7urqNzk4Jh7ygYNRovaMyWae err="unable to create new discovery client connection, could not initialize new discovery client - peer [16Uiu2HAkxgphSqizpEDUUWLospTg7urqNzk4Jh7ygYNRovaMyWae] not connected"
2023-01-04T12:24:34.835Z [ERROR] polygon.network.discovery: Unable to execute bootnode peer discovery: bootnode=16Uiu2HAm7LM5kexwkjy1M4R1hKcptCivX5bPcxgtd7mxrQYQrnsr err="unable to create new discovery client connection, could not initialize new discovery client - peer [16Uiu2HAm7LM5kexwkjy1M4R1hKcptCivX5bPcxgtd7mxrQYQrnsr] not connected
```

Tho, when I attach all the nodes and query each of their secrets and node id, there are no nodes with node id:

```
16Uiu2HAm7LM5kexwkjy1M4R1hKcptCivX5bPcxgtd7mxrQYQrnsr
16Uiu2HAkxgphSqizpEDUUWLospTg7urqNzk4Jh7ygYNRovaMyWae
```

My genesis file tho, looks correct (with these 2 bootnodes above).
```
{
    "name": "polygon-edge",
    "genesis": {
        "nonce": "0x0000000000000000",
        "timestamp": "0x0",
        ...
        ...
    "params": {
        "forks": {
            "homestead": 0,
            "byzantium": 0,
            "constantinople": 0,
            "petersburg": 0,
            "istanbul": 0,
            "EIP150": 0,
            "EIP158": 0,
            "EIP155": 0
        },
        "chainID": 100,
        "engine": {
            "ibft": {
                "epochSize": 100000,
                "type": "PoA",
                "validator_type": "bls"
            }
        },
        "blockGasTarget": 0
    },
    "bootnodes": [
        "/dns4/node-1/tcp/1478/p2p/16Uiu2HAkxgphSqizpEDUUWLospTg7urqNzk4Jh7ygYNRovaMyWae",
        "/dns4/node-2/tcp/1478/p2p/16Uiu2HAm7LM5kexwkjy1M4R1hKcptCivX5bPcxgtd7mxrQYQrnsr"
    ]
}
```

Could you please tell me where are these 'uknown' node ids coming from ?

## Your environment
- MacOSX - Docker compose 3.5
- The version of the Polygon Edge:   
  [VERSION INFO]
Release version = v0.6.1

## Steps to reproduce
- Tell us how to reproduce this issue.
1. Have docker and docker compose installed
2. Place these 3 files next to each other and run docker build:
`docker build -t my_polygon_edge_node .`
3. `docker compose up -d`

## Expected behavior
You shall be seeing the same discovery issue. Most probably i'm configuring something wrong I guess, but I do not exactly see where.

Thank you in advance for your help!

[log_node1.txt](https://github.com/0xPolygon/polygon-edge/files/10344242/log_node1.txt)
[log_node2.txt](https://github.com/0xPolygon/polygon-edge/files/10344243/log_node2.txt)
[log_node3.txt](https://github.com/0xPolygon/polygon-edge/files/10344244/log_node3.txt)
[log_node4.txt](https://github.com/0xPolygon/polygon-edge/files/10344245/log_node4.txt)

**Comment by adaki2004** [comment] 2023-01-04 14:03
![kép](https://user-images.githubusercontent.com/51912515/210571587-78ff8006-88c3-46f4-a17e-8dbcbc118523.png)
Something feels not ok with volumes.. Now I exchanged the --data-dir in the command of starting the nodes from
`data` to `polygon-edge/data-X` but still giving the same error :( hmm

**Comment by adaki2004** [comment] 2023-01-04 14:12
Ok, corrected that the nodes accessing the same volumes now - but issue still persists.
![kép](https://user-images.githubusercontent.com/51912515/210573562-87c66bf2-7e2c-477d-9377-b339a5e43c4c.png)

**Comment by ivanbozic21** [comment] 2023-01-05 09:48
Hi @adaki2004 
Thank you for your patience, and we identified the issue with docker files and we're waiting for PR fix to be reviewed and merged with the develop branch or you or you change the branch to the one from this

You're free to change the branch and use this one:

https://github.com/0xPolygon/polygon-edge/pull/1096

Let us know if you will need any more assistance.

**Comment by adaki2004** [comment] 2023-01-09 14:26
Hello @ivanbozic21 ,

I appreciate your help. It indeed helped me with the docker-compose but my final environment is Kubernetes.
Therefore i converted the running application of the docker-compose to k8s config with kompose convert.

And now on k8s (minikube) i get the same discovery issue now. Most probably i'm doing something wrong - with the network.
Could you please help me out ? I put my description into the PR (maybe wrong place feel free to move/remove or want me to put it somewhere else)

https://github.com/0xPolygon/polygon-edge/pull/1096

Is it possible to re-open this, or shall I create a new one for that ?

**Comment by adaki2004** [comment] 2023-01-09 16:26
> 

Could you help me with the one i shared recently ? :)

**Comment by epikichi** [comment] 2023-01-10 11:33
Hi @adaki2004! 

Can you provide some details on the following:
- How you built the binary for your image
- What is the K8s cluster domain? (default on minikube is `cluster.local`)

Also, if possible, can we enable debug logs on the nodes? You can add in the server flag `--log-level debug` in the compose file or pod container commands.

**Comment by adaki2004** [comment] 2023-01-10 13:33
> Hi @adaki2004!
> 
> Can you provide some details on the following:
> 
>     * How you built the binary for your image
> 
>     * What is the K8s cluster domain? (default on minikube is `cluster.local`)
> 
> 
> Also, if possible, can we enable debug logs on the nodes? You can add in the server flag `--log-level debug` in the compose file or pod container commands.

Hello @epikichi,

Thanks for getting back to me!

1. In my docker-compose config i use this image: danielkeszeyns898/polygon_edge_node - and that image is built from the attached Docker + polygon-edge.sh (both renamed to .txt to be able to uploaded). I'm attaching all of the files (docker-compose and the generated - deployments and pods via `kompose convert -f docker-compose.yaml`
2. kubectl is configured to use minikube and the default namespace.

This is /was my workflow: (Steps to reproduce)
Prerequisites: 
1. Build the Dockerfile and tag it:
`docker build -t danielkeszeyns898/polygon_edge_node .`
2. Upload to dockerhub 
`docker push danielkeszeyns898/polygon_edge_node`
3. To have the deployments on K8S running the conversion:
`kompose convert -f docker-compose.yml`

Running (with docker-compose):
`docker compose up -d` --> Works as expected, everything in sync, discovery OK.

Running with (kubectl / minikube)
`minikube start`
`kubectl apply -f .` --> I see the volumes mounted corre
ctly and nodes have access to the correct genesis.json.

I'm attaching all the files i'm using + the logs (with `--log-level debug`) from node-1 (one bootnode) and node-3 (non bootnode).
If you could reproduce these steps and let me know your thoughts or steps to resolve i'd highly appreciate it.

[docker-compose.txt](https://github.com/0xPolygon/polygon-edge/files/10383185/docker-compose.txt)
[Dockerfile.txt](https://github.com/0xPolygon/polygon-edge/files/10383186/Dockerfile.txt)
[log_node1.txt](https://github.com/0xPolygon/polygon-edge/files/10383187/log_node1.txt)
[node-4-service.txt](https://github.com/0xPolygon/polygon-edge/files/10383188/node-4-service.txt)
[node-3-service.txt](https://github.com/0xPolygon/polygon-edge/files/10383189/node-3-service.txt)
[node-4-pod.txt](https://github.com/0xPolygon/polygon-edge/files/10383190/node-4-pod.txt)
[node-2-service.txt](https://github.com/0xPolygon/polygon-edge/files/10383191/node-2-service.txt)
[node-2-pod.txt](https://github.com/0xPolygon/polygon-edge/files/10383192/node-2-pod.txt)
[log_node3.txt](https://github.com/0xPolygon/polygon-edge/files/10383193/log_node3.txt)
[node-1-service.txt](https://github.com/0xPolygon/polygon-edge/files/10383194/node-1-service.txt)
[data-persistentvolumeclaim.txt](https://github.com/0xPolygon/polygon-edge/files/10383195/data-persistentvolumeclaim.txt)
[polygon-edge.txt](https://github.com/0xPolygon/polygon-edge/files/10383196/polygon-edge.txt)
[polygon-edge-docker-networkpolicy.txt](https://github.com/0xPolygon/polygon-edge/files/10383197/polygon-edge-docker-networkpolicy.txt)
[node-3-pod.txt](https://github.com/0xPolygon/polygon-edge/files/10383198/node-3-pod.txt)
[init-deployment.txt](https://github.com/0xPolygon/polygon-edge/files/10383199/init-deployment.txt)
[node-1-pod.txt](https://github.com/0xPolygon/polygon-edge/files/10383200/node-1-pod.txt)

**Comment by epikichi** [comment] 2023-01-10 15:53
I took a brief look at the configurations you had. Do the pods/services expose port `1478` for Libp2p consensus communication? That might be the cause of the timeout in the logs.

**Comment by adaki2004** [comment] 2023-01-10 16:08
@epikichi 
![image](https://user-images.githubusercontent.com/51912515/211602327-db3402e8-dcf7-4b7b-ac4c-cdc3b30813e0.png)
Hmm, according to this, no. But based on the image (Dockerfile), it shall be exposed, no ? (I'm relatively new to K8s - so most probably i'm wrong here.)

**Closed as completed** 2023-01-10 16:08 UTC

**Comment by epikichi** [comment] 2023-01-10 16:25
Thanks for the context, @adaki2004! Glad to have more adopters running in K8s.

Because the services you provided proxy traffic to the validators, the service itself will need to have the `1478` port defined for the proxy to accept Lib2p traffic. If you look at the logs provided, the resolved DNS for `node-n` is a service IP rather than a pod IP.

[Headless Services](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) would be a great fit for the validator's use case. 
> For headless Services, a cluster IP is not allocated, kube-proxy does not handle these Services, and there is no load balancing or proxying done by the platform for them. How DNS is automatically configured depends on whether the Service has selectors definedFor headless Services, a cluster IP is not allocated, kube-proxy does not handle these Services, and there is no load balancing or proxying done by the platform for them. How DNS is automatically configured depends on whether the Service has selectors defined

**Comment by adaki2004** [comment] 2023-01-10 16:28
Thanks @epikichi !
Since i created the services and deployments for K8S with kompose convert - i did it on purpose, i'm less experienced with K8S :) Would you be kind to point me out to the configuration setting, where can I add the expose port ?
