### ISSUE TITLE
Error getting storage snapshot when deploying a smart contract to private blockchain via hardhat

### ISSUE THREAD

**Issue by e74000** [0xPolygon/polygon-edge#64] opened 2021-06-10 11:24 UTC
### Description

When using hardhat to deploy a copy of the sample Greeter.sol script to a private polygon blockchain, I get the error: `error getting storage snapshot` in the server log. I am a bit of a noob at this so please correct me if I'm doing something stupid.

### Your environment

OS: Manjaro linux 5.10.41
Ver: 0.1.0-dev

### Steps to reproduce

- To reproduce start a polygon blockchain, exactly copying this guide: https://sdk-docs.polygon.technology/docs/how-tos/howto-set-ibft,
- Start a JsonRPC server with `go run main.go --chain genesis.json --log-level debug`,
- Compile the sample script in hardhat with `npx hardhat compile` in the sample repository,
- Your JsonRPC servers ip and port, + an account in the `hardhat.config.js` config file
- Run the provided script to deploy the compiled smart contract with `npx hardhat run scripts/sample-script.js --network polygon`

### Expected behaviour

The simple hello world script should be deployed to the blockchain.

### Actual behaviour

In hardhat you get the error `HardhatError: HH110: Invalid JSON-RPC response received: {"code":-32603,"message":"internal error"}`
In the polygon server you get the error `[ERROR] polygon.dispatcher: failed to dispatch: method=eth_estimateGas err="error getting storage snapshot"`

### Logs

```
2021-06-10T13:17:22.133+0100 [DEBUG] polygon.dispatcher: request: method=web3_clientVersion id=1
2021-06-10T13:17:22.144+0100 [DEBUG] polygon.dispatcher: request: method=eth_chainId id=2
2021-06-10T13:17:22.154+0100 [DEBUG] polygon.dispatcher: request: method=eth_chainId id=3
2021-06-10T13:17:22.163+0100 [DEBUG] polygon.dispatcher: request: method=eth_estimateGas id=4
2021-06-10T13:17:22.163+0100 [ERROR] polygon.dispatcher: failed to dispatch: method=eth_estimateGas err="error getting storage snapshot"
```

### Proposed solution

No idea how to fix it, but I found that the file giving the error was minimal/server.go

**Comment by fastepic** [comment] 2021-06-11 06:56
My small investigation - when send transaction ( like deploy contract ) with not value set or from account which has not coin or not used yet when I see Error: Invalid JSON RPC response: {"code":-32603,"message":"internal error"}. When I want second time send to the same node correct transaction from correct address I have error like the same or not answer ... after restart this node and repeat correct transaction all is ok.

**Comment by lazartravica** [comment] 2021-06-14 12:54
Hello @e74000, thank you for the issue but I was not able to reproduce the issue with the steps provided.

The command you have supplied: `go run main.go --chain genesis.json --log-level debug` is invalid, you should use the commands listed in the IBFT setup docs which you've linked.

This is at the end of my `hardhat.config.js`:
```
module.exports = {
  solidity: "0.7.3",
  defaultNetwork: "polygon-sdk",
  networks: {
    "polygon-sdk": {
      url: "http://localhost:10002",
      accounts: [PRIVATE_KEY]
    }
  },
};
```

I was able to deploy the contract:

```
npx hardhat run scripts/sample-script.js --network polygon-sdk
Greeter deployed to: 0x26d60655cDAAB015bDF75e14c29c1e8F2B5bEcF4
```

And I was able to deploy & invoke the Greeter contract by running the supplied sample-test.js:

```
$ npx hardhat test


  Greeter
    ✓ Should return the new greeting once it's changed (8268ms)


  1 passing (8s)
```

Could you please update your local `develop` branch, setup the cluster again using instructions here https://sdk-docs.polygon.technology/docs/how-tos/howto-set-ibft and let me know if the issues persist?

**Comment by mrwillis** [comment] 2021-06-16 20:46
I'm also experiencing this issue using `truffle` trying to deploy a simple contract causing truffle to hang 

```

2021-06-16T20:28:16.061Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_estimateGas err="error getting storage snapshot"
then some time later...

2021-06-16T20:28:57.951Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBlockByNumber err="unable to get block by num 18811"

2021-06-16T20:33:38.824Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getCode err="error getting storage snapshot"
```

I'm on commit `42be5f9730b1601872609e7fbed3d92e24193dc4` on develop

I have a 4 node cluster. Repo steps are broadly

```
./main server --data-dir ./validator-n --chain genesis.json --grpc :10000 --libp2p :10001 --jsonrpc :10002 --seal

on each node
```

connectivity is fine. Verified through metamask. Sending simple balance transfers is also fine.

**Comment by lazartravica** [comment] 2021-06-18 12:32
The issue is that the account you are trying to send these funds from is uninitialized, meaning it has 0 balance and is not found in the storage trie.

We will improve on this so that you can still run estimateGas and other RPC calls even if the account is uninitialized, and for calls that require the account to have a certain balance, provide a more meaningful error message, other than `error getting storage snapshot`.

Before I close this issue, @mrwillis can you please confirm that the private key you have configured in truffle is in fact associated with the premined address in the genesis block?

**Comment by lazartravica** [comment] 2021-07-21 06:58
Issue has been fixed by implementing more meaningful messages that indicate regular behaviour and not an error on trying to interact with an uninitialized address in the world state.

The only JSON-RPC endpoint that was fixed, which returned an `internal error` JSON-RPC response on trying to interact with an uninitialized address was the `eth_getCode`, if you notice anything else please open another issue.

**Closed as completed by lazartravica** 2021-07-21 06:58 UTC
Labels: info needed
