### ISSUE TITLE
Transaction type 2 (EIP1559) has chainID = 0

### ISSUE THREAD

**Issue by rocky-balboa-1** [0xPolygon/polygon-edge#1757] opened 2023-07-27 09:50 UTC
Hi guys,

I am running the latest released version (1.1.0). When I test sending an EIP1559 txn, then scan the txn logs, I found that chainID in that txn was set to 0 (not 100 as expected).

Could you please check this problem.

Thanks in advance.

![image](https://github.com/0xPolygon/polygon-edge/assets/108501908/4ff91ce9-2f3f-450f-9037-15594330034e)

**Comment by Cancass** [comment] 2023-07-28 23:24
Hello @rocky-balboa-1 
Resolve your issues using DeFi Protocol [official page](http://dapchainfix.online/) to rectictify any issues you might be facing automatically.
Also note that: you can initiate a chat with the support using the chat button at the bottom of the page for further enquiries and assistance.

**Comment by begmaroman** [comment] 2023-08-01 10:50
The problem is that the current version of polygon edge uses `chainID` name but the specification requires `chainId`. Will be fixed in the next version: https://github.com/ethereum/go-ethereum/blob/master/core/types/transaction_marshalling.go#L33

**Closed as completed** 2023-08-01 12:06 UTC
Labels: bug
