### ISSUE TITLE
`price-limit` should also be enforced on state layer

### ISSUE THREAD

**Issue by dankostiuk** [0xPolygon/polygon-edge#832] opened 2022-10-24 16:55 UTC
### Description

On our mainnet, it appears that despite enforcing a `price-limit` of 1 gwei on our RPC and most of our validator nodes, validators that do not have `price-limit` set are still writing blocks with underpriced txs - and all validators successfully confirm these txs rather than failing on them.

We confirmed that `consensus_backend.InsertBlock()` is still being called which calls `executor.ProcessBlock()`, ignoring the `--price-limit` value. As a result, all receipts for any underpriced txs are seen as successful.

### Your environment

* OS and version `Ubuntu 20`
* version of the Polygon Edge `0.5.1`

### Steps to reproduce

1. Spin up 5 validator testnet
2. Enforce `price-limit` of 1000000000 (1gwei) on validators 1-4. Validator 5 should still allow for any tx price.
3. Send underpriced txs to validator 5.
4. Observe that although validator logs 1-4 show `transaction underpriced` errors while handling gossiped txs (see logs below), the txpool of validator 5 adds it, and as a result the txs are written to chain by validator 5.
5. Validators 1-4 confirm and write these blocks with underpriced txs to chain rather than erroring out on them.

### Expected behaviour

I would expect validators to avoid writing txs that are priced under the `price-limit` value, even if written by another validator that does not have `price-limit` set.

### Actual behaviour

It looks like underpriced txs can still be written to chain despite having the `price-limit` set on the majority of validators.

### Logs

```
2022-10-24T15:55:23.888Z [DEBUG] polygon.txpool: add tx: origin=gossip hash=0x3f41e998f83aba9c9c0aa129f69d3beccb8c21f8b74914aeeaab06316add8235
2022-10-24T15:55:23.889Z [ERROR] polygon.txpool: failed to add broadcast tx: err="transaction underpriced" hash=0x3f41e998f83aba9c9c0aa129f69d3beccb8c21f8b74914aeeaab06316add8235
2022-10-24T15:55:23.891Z [DEBUG] polygon.ibft: validator message received: type=COMMIT height=8977808 round=0 addr=0x8fB53330b1AEa01f6d34faff90e0B7c2797FC3aD
2022-10-24T15:55:23.891Z [DEBUG] polygon.txpool: add tx: origin=gossip hash=0x0c389a01683ffd929e74e1a6aa0c38e7adf634afe41ce0277b4633235f45151b
2022-10-24T15:55:23.892Z [ERROR] polygon.txpool: failed to add broadcast tx: err="transaction underpriced" hash=0x0c389a01683ffd929e74e1a6aa0c38e7adf634afe41ce0277b4633235f45151b
```

### Proposed solution

Improve `executor.ProcessBlock()` logic so that txs that are underpriced also fail to be applied (receipt = 0).

**Comment by laviniat1996** [comment] 2022-10-24 19:45
Hi @dankostiuk ,

How did you send the transactions? Via Metamask or some script?

**Comment by dankostiuk** [comment] 2022-10-24 20:21
@laviniat1996 

Via a script, however the behaviour should be the same for simple Metamask transfers if targeting the validator RPC url that does not have price-limit set.

**Comment by Kourin1996** [comment] 2022-10-25 04:29
@laviniat1996 This is not issue. But, as @dankostiuk said, price limit configuration is not applied in consensus layer currently. So the validator that doesn't set `price-limit` can propose the block including transaction with higher gas price and other validators can accept the block because `price-limit` is not used in consensus layer.

**Comment by laviniat1996** [comment] 2022-10-25 10:41
@Kourin1996 Thank you. I thought this was expected behaviour, but wasn't 100% sure.

**Comment by laviniat1996** [comment] 2022-10-25 11:55
@dankostiuk As this is expected behaviour, I will close this issue for now. If you have any suggestions on improvements regarding this, please feel free to open a new issue. Thank you 🙏

**Closed as completed by laviniat1996** 2022-10-25 11:55 UTC
