### ISSUE TITLE
eth_estimateGas transition.apply vs eth_call transition.apply result differs for the same param data

### ISSUE THREAD

**Issue by dankostiuk** [0xPolygon/polygon-edge#444] opened 2022-03-09 20:51 UTC
### Description

Prior to the changes introduced in https://github.com/0xPolygon/polygon-edge/pull/422 , certain transition.apply calls within eth_estimateGas would fail, however in these scenarios eth_estimateGas still returned what looked to be a successful response, returning a value of `GasCap + 1` or `5000001`. A subsequent eth_call using this value would result in a successful transaction.

After pulling in https://github.com/0xPolygon/polygon-edge/pull/422, we were made aware than an error exists in eth_estimateGas, as we now see the following error message:
```
unable to apply transaction even for the highest gas limit 60000000: execution was reverted
```

---

For context, we have some frontend logic that chains the result of an estimateGas call to the actual call. Below you can see that the `data` value is identical for both calls, however each transition.apply in eth_estimateGas fails until we observe an error response with the message above, when we believe this function should in fact response with an estimateGas value.

eth_estimateGas:
```
{"id":1085389008,"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0x78b7bc9fdc7dc431d385d1e18cac6b53ddcf4ba9","to":"0x22b3069a51aa8bddca7cee0e3db460b9da23f379","data":"0x5c11d795000000000000000000000000000000000000000000000001a055690d9db80000000000000000000000000000000000000000000000000004038f617f17b5724200000000000000000000000000000000000000000000000000000000000000a000000000000000000000000078b7bc9fdc7dc431d385d1e18cac6b53ddcf4ba9000000000000000000000000000000000000000000000000000000006227c0ef000000000000000000000000000000000000000000000000000000000000000200000000000000000000000028fe1f46c9c0eef1cdf44c9c504c43e7914320890000000000000000000000003a1c652a4966a68a0ac520d9a8f00463efd5219a"}]}
```

eth_call:
```
{"id":1085389010,"jsonrpc":"2.0","method":"eth_call","params":[{"from":"0x78b7bc9fdc7dc431d385d1e18cac6b53ddcf4ba9","to":"0x22b3069a51aa8bddca7cee0e3db460b9da23f379","data":"0x5c11d795000000000000000000000000000000000000000000000001a055690d9db80000000000000000000000000000000000000000000000000004038f617f17b5724200000000000000000000000000000000000000000000000000000000000000a000000000000000000000000078b7bc9fdc7dc431d385d1e18cac6b53ddcf4ba9000000000000000000000000000000000000000000000000000000006227c0ef000000000000000000000000000000000000000000000000000000000000000200000000000000000000000028fe1f46c9c0eef1cdf44c9c504c43e7914320890000000000000000000000003a1c652a4966a68a0ac520d9a8f00463efd5219a"},"0x1399fa"]}
```

---

We've managed to avoid calling eth_estimateGas altogether and we are currently hardcoding a gasEstimate value of 5000000 for all eth_call requests for this type of transaction -- these transactions then work as expected.

### Your environment

* OS and version `Ubuntu 20`
* version of the Polygon Edge `Release v0.3.0`
* branch that causes this issue `develop`

### Steps to reproduce

Before https://github.com/0xPolygon/polygon-edge/pull/422 :
1. After forking the frontend of sushiswap (https://github.com/sushiswap/sushiswap-interface) and configuring to point to your testnet, attempt to perform any swap transaction, these will make use of the useSwapCallback hook [here](https://github.com/sushiswap/sushiswap-interface/blob/e5c09dea3cb46d89099282757095f29e9cf8b87c/src/hooks/useSwapCallback.ts#L596).
2. Attempt to perform a swap, this will use chained estimateGas + ethCall logic:
```
         return library
              .estimateGas(tx)
              .then((gasEstimate) => {
                return {
                  call,
                  gasEstimate,
                }
              })
```
3. Observe that eth_estimateGas reaches GasCap + 1 limit and responds with a gasEstimate of 5000001
4. The subsequent eth_call will use the above value and the transaction will be successful

After https://github.com/0xPolygon/polygon-edge/pull/422 :
1. After forking the frontend of sushiswap (https://github.com/sushiswap/sushiswap-interface) and configuring to point to your testnet, attempt to perform any swap transaction, these will make use of the useSwapCallback hook [here](https://github.com/sushiswap/sushiswap-interface/blob/e5c09dea3cb46d89099282757095f29e9cf8b87c/src/hooks/useSwapCallback.ts#L596).
2. Observe that eth_estimateGas returns an error response:
```
unable to apply transaction even for the highest gas limit
```
3. No subsequent eth_call can be made unless we hardcode the gas value to something like before (5000001)

### Expected behaviour

The transition.apply result in eth_estimateGas should not differ from the transition.apply result in a eth_call.

At the very least, eth_estimateGas should respond with the block gasLimit if all else fails (as it did before).

### Actual behaviour

eth_estimateGas fails as a result of `e.store.ApplyTxn(header, txn)` returning a result object with Err.data = "execution was reverted" and nil error.

**Comment by zivkovicmilos** [comment] 2022-03-10 12:44
Hey @dankostiuk,

Thank you for opening up this issue 🙏 

When you say fork Sushiswap, do you mean this repo?
https://github.com/sushiswap/sushiswap

Which script are you executing?

**Comment by zivkovicmilos** [comment] 2022-03-10 13:01
@dankostiuk 

Can you please share the data dirs for the chain, along with the genesis file?
I want to have them present if I'm unable to reproduce the problem with the Sushiswap repo.

Please also provide additional steps for reproducing the problem (step 1) 🙏

**Comment by dankostiuk** [comment] 2022-03-10 15:25
> Hey @dankostiuk,
> 
> Thank you for opening up this issue 🙏
> 
> When you say fork Sushiswap, do you mean this repo? https://github.com/sushiswap/sushiswap
> 
> Which script are you executing?

@zivkovicmilos 

We are using a fork of https://github.com/sushiswap/sushiswap-interface and the part of the script that makes a call to estimateGas is right here:

https://github.com/sushiswap/sushiswap-interface/blob/e5c09dea3cb46d89099282757095f29e9cf8b87c/src/hooks/useSwapCallback.ts#L596


> Can you please share the data dirs for the chain, along with the genesis file?
> I want to have them present if I'm unable to reproduce the problem with the Sushiswap repo.
>
> Please also provide additional steps for reproducing the problem (step 1) 🙏

I've shared both data-dir backup and genesis file with you on telegram and will add more info to step 1, thanks 🙏

**Comment by zivkovicmilos** [comment] 2022-03-18 10:13
Closing this issue as it seems to be an unrelated problem.

We've discussed this internally and will start drafting a PR for the concurrency problem that seems to be popping up 🙏

**Closed as completed by zivkovicmilos** 2022-03-18 10:13 UTC
Labels: investigating
