### ISSUE TITLE
POA network stuck in SyncState block 0

### ISSUE THREAD

**Issue by nshCore** [0xPolygon/polygon-edge#622] opened 2022-07-06 01:35 UTC
### Description

i am experiencing issues where running Polygon edge nodes in POA does not get past the 

```
polygon.consensus.ibft: state change: new=SyncState
```

status

I have setup for nodes with the following genesis bootstrap command

node 1
```
polygon-edge genesis --consensus ibft \
--ibft-validator=0x583Df7f66F748e1471C44b6776692C3D1eDB9CB4 \
--bootnode=/ip4/159.65.82.59/tcp/1478/p2p/16Uiu2HAky6cpqQJFneebjfFDWJRUiEtk6UfgpSE6NoPwMfufe1JT \
--ibft-validator=0x7D4fbc4B6C29f47AECE060A533Aee5821FC84f66 \
--bootnode=/ip4/188.166.44.68/tcp/1478/p2p/16Uiu2HAm48J3m7UyB5oKpxK4vQsks3kDdFDs2yhcYct4TN8EoZG8 \
--premine=0xBa59A0EF89Cce1aB7437036dbF55A6Ee8A6E5d6C:100000000000000000000000 \
--premine=0x99dBB17c5Cf65daBCDFD736BA5b7Dc909086328C:100000000000000000000000 \
--premine=0x583Df7f66F748e1471C44b6776692C3D1eDB9CB4:100000000000000000000000 \
--premine=0x7D4fbc4B6C29f47AECE060A533Aee5821FC84f66:100000000000000000000000
```

node2
```
polygon-edge genesis --consensus ibft \
--ibft-validator=0x99dBB17c5Cf65daBCDFD736BA5b7Dc909086328C \
--bootnode=/ip4/138.197.150.216/tcp/1478/p2p/16Uiu2HAkuiq1xd2eZ3pYWT7oiU55TEQcdghgb852ALEE8Gg5gsTJ \
--ibft-validator=0x7D4fbc4B6C29f47AECE060A533Aee5821FC84f66 \
--bootnode=/ip4/188.166.44.68/tcp/1478/p2p/16Uiu2HAm48J3m7UyB5oKpxK4vQsks3kDdFDs2yhcYct4TN8EoZG8 \
--premine=0xBa59A0EF89Cce1aB7437036dbF55A6Ee8A6E5d6C:100000000000000000000000 \
--premine=0x99dBB17c5Cf65daBCDFD736BA5b7Dc909086328C:100000000000000000000000 \
--premine=0x583Df7f66F748e1471C44b6776692C3D1eDB9CB4:100000000000000000000000 \
--premine=0x7D4fbc4B6C29f47AECE060A533Aee5821FC84f66:100000000000000000000000
```

node3
```
polygon-edge genesis --consensus ibft \
--ibft-validator=0x99dBB17c5Cf65daBCDFD736BA5b7Dc909086328C \
--bootnode=/ip4/138.197.150.216/tcp/1478/p2p/16Uiu2HAkuiq1xd2eZ3pYWT7oiU55TEQcdghgb852ALEE8Gg5gsTJ \
--ibft-validator=0x583Df7f66F748e1471C44b6776692C3D1eDB9CB4 \
--bootnode=/ip4/159.65.82.59/tcp/1478/p2p/16Uiu2HAky6cpqQJFneebjfFDWJRUiEtk6UfgpSE6NoPwMfufe1JT \
--premine=0xBa59A0EF89Cce1aB7437036dbF55A6Ee8A6E5d6C:100000000000000000000000 \
--premine=0x99dBB17c5Cf65daBCDFD736BA5b7Dc909086328C:100000000000000000000000 \
--premine=0x583Df7f66F748e1471C44b6776692C3D1eDB9CB4:100000000000000000000000 \
--premine=0x7D4fbc4B6C29f47AECE060A533Aee5821FC84f66:100000000000000000000000
```

node4
```
polygon-edge genesis --consensus ibft \
--ibft-validator=0x99dBB17c5Cf65daBCDFD736BA5b7Dc909086328C \
--bootnode=/ip4/138.197.150.216/tcp/1478/p2p/16Uiu2HAkuiq1xd2eZ3pYWT7oiU55TEQcdghgb852ALEE8Gg5gsTJ \
--ibft-validator=0x583Df7f66F748e1471C44b6776692C3D1eDB9CB4 \
--bootnode=/ip4/159.65.82.59/tcp/1478/p2p/16Uiu2HAky6cpqQJFneebjfFDWJRUiEtk6UfgpSE6NoPwMfufe1JT \
--premine=0xBa59A0EF89Cce1aB7437036dbF55A6Ee8A6E5d6C:100000000000000000000000 \
--premine=0x99dBB17c5Cf65daBCDFD736BA5b7Dc909086328C:100000000000000000000000 \
--premine=0x583Df7f66F748e1471C44b6776692C3D1eDB9CB4:100000000000000000000000 \
--premine=0x7D4fbc4B6C29f47AECE060A533Aee5821FC84f66:100000000000000000000000
```

all four nodes are being started with the following command

```
polygon-edge server --data-dir kmc --chain genesis.json  --libp2p 0.0.0.0:1478 --jsonrpc 0.0.0.0:8545 --seal --block-time 2 --ibft-base-timeout 15 --grpc-address 0.0.0.0:9632
```

all four nodes find each other and establish peer connections

node1
```
2022-07-06T01:13:49.237Z [INFO]  polygon.consensus.ibft: state change: new=SyncState
2022-07-06T01:13:50.106Z [INFO]  polygon.network: Peer connected: id=16Uiu2HAm5aBhDtepHyptqC3vyQnGQ7rTMmWXdcQGCN9PRVn67eKY
2022-07-06T01:13:50.129Z [INFO]  polygon.network: Peer connected: id=16Uiu2HAm48J3m7UyB5oKpxK4vQsks3kDdFDs2yhcYct4TN8EoZG8
```

```
root@node-1:~# polygon-edge peers list

[PEERS LIST]
Number of peers: 3

[0] = 16Uiu2HAm5aBhDtepHyptqC3vyQnGQ7rTMmWXdcQGCN9PRVn67eKY
[1] = 16Uiu2HAm48J3m7UyB5oKpxK4vQsks3kDdFDs2yhcYct4TN8EoZG8
[2] = 16Uiu2HAky6cpqQJFneebjfFDWJRUiEtk6UfgpSE6NoPwMfufe1JT
```

node2
```
2022-07-06T01:14:05.590Z [INFO]  polygon.consensus.ibft: state change: new=SyncState
2022-07-06T01:14:06.153Z [INFO]  polygon.network: Peer connected: id=16Uiu2HAm48J3m7UyB5oKpxK4vQsks3kDdFDs2yhcYct4TN8EoZG8
2022-07-06T01:14:06.263Z [INFO]  polygon.network: Peer connected: id=16Uiu2HAkuiq1xd2eZ3pYWT7oiU55TEQcdghgb852ALEE8Gg5gsTJ
2022-07-06T01:14:09.484Z [INFO]  polygon.network: Peer connected: id=16Uiu2HAm5aBhDtepHyptqC3vyQnGQ7rTMmWXdcQGCN9PRVn67eKY
```

```
root@node-2:~# polygon-edge peers list

[PEERS LIST]
Number of peers: 3

[0] = 16Uiu2HAm48J3m7UyB5oKpxK4vQsks3kDdFDs2yhcYct4TN8EoZG8
[1] = 16Uiu2HAkuiq1xd2eZ3pYWT7oiU55TEQcdghgb852ALEE8Gg5gsTJ
[2] = 16Uiu2HAm5aBhDtepHyptqC3vyQnGQ7rTMmWXdcQGCN9PRVn67eKY
```

node3
```
2022-07-06T01:14:05.590Z [INFO]  polygon.consensus.ibft: state change: new=SyncState
2022-07-06T01:14:06.153Z [INFO]  polygon.network: Peer connected: id=16Uiu2HAm48J3m7UyB5oKpxK4vQsks3kDdFDs2yhcYct4TN8EoZG8
2022-07-06T01:14:06.263Z [INFO]  polygon.network: Peer connected: id=16Uiu2HAkuiq1xd2eZ3pYWT7oiU55TEQcdghgb852ALEE8Gg5gsTJ
2022-07-06T01:14:09.484Z [INFO]  polygon.network: Peer connected: id=16Uiu2HAm5aBhDtepHyptqC3vyQnGQ7rTMmWXdcQGCN9PRVn67eKY
```

```
root@node-3:~# polygon-edge peers list

[PEERS LIST]
Number of peers: 3

[0] = 16Uiu2HAkuiq1xd2eZ3pYWT7oiU55TEQcdghgb852ALEE8Gg5gsTJ
[1] = 16Uiu2HAm5aBhDtepHyptqC3vyQnGQ7rTMmWXdcQGCN9PRVn67eKY
[2] = 16Uiu2HAky6cpqQJFneebjfFDWJRUiEtk6UfgpSE6NoPwMfufe1JT
```

node4
```
2022-07-06T01:13:49.289Z [INFO]  polygon.consensus.ibft: state change: new=SyncState
2022-07-06T01:13:50.060Z [INFO]  polygon.network: Peer connected: id=16Uiu2HAkuiq1xd2eZ3pYWT7oiU55TEQcdghgb852ALEE8Gg5gsTJ
2022-07-06T01:13:54.583Z [INFO]  polygon.network: Peer connected: id=16Uiu2HAm48J3m7UyB5oKpxK4vQsks3kDdFDs2yhcYct4TN8EoZG8
```

```
root@node-4:~# polygon-edge peers list

[PEERS LIST]
Number of peers: 3

[0] = 16Uiu2HAkuiq1xd2eZ3pYWT7oiU55TEQcdghgb852ALEE8Gg5gsTJ
[1] = 16Uiu2HAm48J3m7UyB5oKpxK4vQsks3kDdFDs2yhcYct4TN8EoZG8
[2] = 16Uiu2HAky6cpqQJFneebjfFDWJRUiEtk6UfgpSE6NoPwMfufe1JT
```

polygon-edge IBFT for each node shows it is at a block height of 0

node1
```
root@node-1:~# polygon-edge ibft snapshot

[IBFT SNAPSHOT]
Block = 0
Hash  = 0x3913389a3e2c901f1d28b8ddc67e812427f988031113ef5c0d0251149e29f044

[VOTES]
No votes found

[VALIDATORS]
ADDRESS
0x583Df7f66F748e1471C44b6776692C3D1eDB9CB4
0x7D4fbc4B6C29f47AECE060A533Aee5821FC84f66
```

node2
```
root@node-2:~# polygon-edge ibft snapshot

[IBFT SNAPSHOT]
Block = 0
Hash  = 0xa320e7ef2f0b52419ff9f76056439fde38bb9a670c4da430571c4fd4aa87b66d

[VOTES]
No votes found

[VALIDATORS]
ADDRESS
0x99dBB17c5Cf65daBCDFD736BA5b7Dc909086328C
0x7D4fbc4B6C29f47AECE060A533Aee5821FC84f66
```

node3
```
root@node-3:~# polygon-edge ibft snapshot

[IBFT SNAPSHOT]
Block = 0
Hash  = 0xee486f45377317c30e3e8b36ba52600572d4323b7556b347e7a333fb6c84860e

[VOTES]
No votes found

[VALIDATORS]
ADDRESS
0x99dBB17c5Cf65daBCDFD736BA5b7Dc909086328C
0x583Df7f66F748e1471C44b6776692C3D1eDB9CB4
```

node4
```
root@node-4:~# polygon-edge ibft snapshot

[IBFT SNAPSHOT]
Block = 0
Hash  = 0xee486f45377317c30e3e8b36ba52600572d4323b7556b347e7a333fb6c84860e

[VOTES]
No votes found

[VALIDATORS]
ADDRESS
0x99dBB17c5Cf65daBCDFD736BA5b7Dc909086328C
0x583Df7f66F748e1471C44b6776692C3D1eDB9CB4
```

I can broadcast transactions to the nodes but they sit in the node tx pool as pending

for example

```
curl  http://188.166.44.68:8545 -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"txpool_content","params":[],"id":1}'
{"jsonrpc":"2.0","id":1,"result":{"pending":{},"queued":{"0xBa59A0EF89Cce1aB7437036dbF55A6Ee8A6E5d6C":{"2":{"nonce":"0x2","gasPrice":"0x3b9aca00","gas":"0x5208","to":"0x8170E9C54470b94F70b1ca7eB68C2184A91cAC49","value":"0x8ac7230489e80000","input":"0x","hash":"0xb232f1bda192ec8b7aaef3179c95e0a4a0e3ba05b23281f32dad9be86e446df0","from":"0xBa59A0EF89Cce1aB7437036dbF55A6Ee8A6E5d6C","blockHash":"0x0000000000000000000000000000000000000000000000000000000000000000","blockNumber":null,"transactionIndex":null}}}}}%
```

```
curl  http://188.166.44.68:8545 -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"txpool_inspect","params":[],"id":1}'
{"jsonrpc":"2.0","id":1,"result":{"pending":{},"queued":{"0xBa59A0EF89Cce1aB7437036dbF55A6Ee8A6E5d6C":{"2":"10000000000000000000 wei + 21000 gas x 1000000000 wei"}},"currentCapacity":1,"maxCapacity":4096}}%
```

```
curl  http://188.166.44.68:8545 -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"txpool_status","params":[],"id":1}'
{"jsonrpc":"2.0","id":1,"result":{"pending":0,"queued":1}}%
```

### Your environment

* OS and version
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

* version of the Polygon Edge
```
v0.4.1+82442a45
```

* branch that causes this issue
```
develop commit 82442a454a55dbb790a6d087ea95ae8ec83a48c5
```

### Steps to reproduce

* Tell us how to reproduce this issue <br />
build from develop commit hash above and run genesis command and server run command provided

* Where the issue is, if you know <br />
nodes not coming to quorum in POA, processing transactions and producing new blocks

* Which commands triggered the issue, if any

### Expected behaviour

Nodes should form a quorum and produce blocks processing broadcasted tx

### Actual behaviour

nodes do not move past SyncState, no blocks produces no transactions verified

### Logs

Please paste any logs here that demonstrate the issue, if they exist

### Proposed solution

If you have an idea of how to fix this issue, please write it down here, so we can begin discussing it

**Comment by laviniat1996** [comment] 2022-07-07 16:12
Hello @nshCore ,
Thank you for opening this issue!

Firstly, I would kindly ask you to make sure you are running all the nodes with the same config file. You can use the command `polygon-edge server export ` , which will generate the config file. After this, you can modify the config file to your needs and use it for all the nodes.

Please let me know how it goes.

**Comment by Kourin1996** [comment] 2022-07-16 05:06
@nshCore Hello, each genesis file seems to have different validator set, which is given by `--ibft-validator`. This validators is stored in genesis header, so the headers with different IBFT validator set returns different hashes. Validator can't join consensus if their genesis hashes are different. Ideally all nodes should have same genesis.json (or the genesis.json generated by `genesis` command with same arguments) Could you please try to generate genesis.json and run nodes again?

**Comment by Kourin1996** [comment] 2022-07-16 06:05
@nshCore Please note that genesis block is set in localstorage when node starts. I recommend you to delete all data-dir before regenerating genesis.json

**Comment by zivkovicmilos** [comment] 2022-07-19 08:08
Hey @nshCore,

Were you able to reproduce this issue with the latest develop branch and @Kourin1996's instructions?

**Comment by zivkovicmilos** [comment] 2022-07-25 10:53
@nshCore 

Closing this issue as it seems to be a misconfig.

Please open a new one if it persists 🙏

**Closed as completed by zivkovicmilos** 2022-07-25 10:53 UTC
Labels: info needed
